[general]
framerate = 60
autosens = 1
bars = 80

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
channels = mono
mono_option = average

[smoothing]
noise_reduction = 35
; waves = 1
monstercat = 1