[general]
framerate = 60
autosens = 1
; sensitivity=100
bars = 50

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
channels = mono
mono_option = average

[smoothing]
noise_reduction = 15
waves = 1
; monstercat = 1

[eq]
1 = 1.2
2 = 1.4
3 = 1.5
4 = 1.22
5 = 1.1
6 = 1.1